#! /bin/sh

# Launch sxhkd
sxhkd &

# Launch polybar
~/.config/polybar/launch.sh &

# Launch notifications
dunst &

#Set background
feh --bg-fill Pictures/Pape.png &

# Autohide the cursor when inactive
unclutter --ignore-scrolling &

# Set the cursor
xsetroot -cursor_name left_ptr 

# Desktops
bspc monitor -d Terminals Broswer Code Social V VI VII VIII IX X

# Border and Gap
bspc config border_width         2
bspc config window_gap          10

# Configuration
bspc config split_ratio          0.50

# Mouse
bspc config click_to_focus	 	button1
bspc config focus_follows_pointer 	true

# Monocle mode settings
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config paddingless_monocle	 true

# Themes
bspc config normal_border_color		"#4c566a"
bspc config focused_border_color	"#88c0d0"
bspc config presel_feedback_color	"#88c0d0"




